# Generated by Django 5.1.2 on 2024-11-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_camera_address_camera_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='inout',
            field=models.CharField(choices=[('IN', 'Вход'), ('OUT', 'Выход')], default='IN', max_length=5, verbose_name='Направление'),
        ),
    ]
