# Generated by Django 5.1.2 on 2024-11-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_camera_inout'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='allowed',
            field=models.TextField(blank=True, null=True, verbose_name='Разрешённые'),
        ),
    ]
