# Generated by Django 5.1.3 on 2024-11-23 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='device',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('OPENING', 'Открывается'), ('CLOSING', 'Закрывается')], default='CLOSED', max_length=7, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
