# Generated by Django 5.1.3 on 2024-11-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_location_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('OPENING', 'Открывается'), ('CLOSING', 'Закрывается')], default='OPENING', max_length=7, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.camera', verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='event',
            name='inout',
            field=models.CharField(blank=True, choices=[('IN', 'Вход'), ('OUT', 'Выход')], default='IN', max_length=5, null=True, verbose_name='Направление'),
        ),
    ]
