# Generated by Django 5.1.3 on 2024-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_status_alter_event_camera_alter_event_inout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='inout',
            field=models.CharField(blank=True, choices=[('IN', 'Вход'), ('OUT', 'Выход')], max_length=5, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('OPENING', 'Открывается'), ('CLOSING', 'Закрывается')], max_length=7, null=True, verbose_name='Статус'),
        ),
    ]
