# Generated by Django 5.1.3 on 2024-12-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_event_inout_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='opened_by',
            field=models.CharField(blank=True, choices=[('IN', 'Вход'), ('OUT', 'Выход')], max_length=5, null=True, verbose_name='Открыто камерой'),
        ),
        migrations.AddField(
            model_name='location',
            name='opened_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payload',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('OPENING', 'Открывается'), ('CLOSING', 'Закрывается'), ('ERROR', 'Ошибка')], max_length=7, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт'), ('OPENING', 'Открывается'), ('CLOSING', 'Закрывается'), ('ERROR', 'Ошибка')], default='CLOSED', max_length=7, verbose_name='Статус'),
        ),
    ]
