# Generated by Django 5.1.4 on 2024-12-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='mode',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Ручной'), ('AUTOCLOSE', 'Автоматически закрыт')], default='MANUAL', max_length=10, null=True, verbose_name='Статус'),
        ),
    ]
