# Generated by Django 5.1.4 on 2025-01-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_location_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cloud_url',
            field=models.URLField(blank=True, null=True, verbose_name='Фото в облаке'),
        ),
    ]
